version: "3.7"

services:
  keycloak_mysql:
    image: mysql:5.7
    volumes:
      - ./volumes/keycloak:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: keycloak
      MYSQL_USER: keycloak
      MYSQL_PASSWORD: password
    container_name: keycloak_mysql

  keycloak:
    image: quay.io/keycloak/keycloak
    ports:
      - 8080:8080
    environment:
      DB_ADDR: keycloak_mysql
      DB_USER: root
      DB_PASSWORD: root
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
    container_name: keycloak
    healthcheck:
      test: ["CMD", "curl", "http://localhost:8080/auth/realms/yata/protocol/openid-connect/certs"]
      interval: 10s
      retries: 20

  mongodb:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - ./volumes/mongo:/data/db

  keycloak_proxy:
    image: keycloak_proxy
    ports:
     - 9998:9998
    environment:
      KEYCLOAK_PROXY_CLIENT_ID: keycloak_proxy
      KEYCLOAK_PROXY_REALM: yata
      KEYCLOAK_PROXY_KEYCLOAK_SERVER: keycloak
      KEYCLOAK_PROXY_PORT: 9998
    container_name: keycloak_proxy
    depends_on:
      keycloak:
        condition: service_healthy

  api:
    image: yata_api
    ports:
      - 9999:9999
    environment:
      YATA_API_KEYCLOAK_PROXY_ROOT: keycloak_proxy
      YATA_API_KEYCLOAK_PROXY_PORT: 9998
    depends_on:
      keycloak_proxy:
        condition: service_started
    restart: on-failure

  frontend:
    image: yata_frontend_webapp
    ports:
      - 8000:80
